version: '3.8'
services:
  dev:
    image: notification-micro:0.0.1
    build:
      context: .
      dockerfile: ./Dockerfile
    command: npm run start
    ports:
      - '3000:3000'
    environment:
      DB_HOST: mongodb
    networks:
      - nestjs-network
    depends_on:
      - mongodb
    volumes:
      - .:/src
      - /src/node_modules
    restart: unless-stopped
  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes: 
      - /database:/data/db
    ports:
      - '27018'
    networks:
      - nestjs-network
    restart: always

networks:
  nestjs-network:
    driver: bridge